### ISSUE TITLE
Bug in MT6835.cpp: register write command wrong

### ISSUE THREAD

**Issue by c031917** [simplefoc/Arduino-FOC-drivers#19]
in file MT6835.cpp the line 261
**cmd.cmd = MT6835_OP_READ;**
must be:
**cmd.cmd = MT6835_OP_WRITE;**

Cheers
Husky

**Comment by runger1101001** [comment]
Thanks for reporting it and for testing out the driver!! It will be fixed in the next release.

**Comment by runger1101001** [comment]
Fixed in 9b03b5d9e9a298714a90b18f2842c639c21bb693

**Comment by runger1101001** [comment]
This has been merged and released
