### ISSUE TITLE
[FEATURE] Allowing to choose SPI pins 

### ISSUE THREAD

**Issue by sylque** [simplefoc/Arduino-FOC-drivers#37]
_This is a duplicate of https://github.com/simplefoc/Arduino-FOC/issues/375_

**Is your feature request related to a problem? Please describe.**
On my ESP32, I can choose any GPIO pins for SPI. Unfortunately, it seems SimpleFOCDrivers only allows for the two sets of default SPI pins (HSPI and VSPI), like this:
```c++
static SPIClass spi(HSPI);
sensor.init(&spi);
```

**Describe the solution you'd like**
Either:
```c++
MagneticSensorAS5048A g_sensorX(int8_t sck=-1, int8_t miso=-1, int8_t mosi=-1, int8_t ss=-1);
```
or:
```c++
sensor.init(int8_t sck=-1, int8_t miso=-1, int8_t mosi=-1, int8_t ss=-1);
```

As a side note, is there any reason why half the SPI parameters (namely SPISettings and nCS) are passed in the sensor constructor whereas the other half (SPIClass) is passed in sensor.init()? This makes things hard to grasp.

**Comment by runger1101001** [comment]
Hi there,

I think you can already do this:

```
    SPIClass mySPI(HSPI);
    mySPI.begin(PIN_CLK, PIN_MISO, PIN_MOSI);
    sensor.init(&mySPI);
```

Please let me know if this solves your problem?

**Comment by sylque** [comment]
Yes, this should work! I will post the result here.

**Comment by sylque** [comment]
It works perfectly, thank you very much.

Now I have 3 places with SPI settings instead of two :-) (sensor constructor, sensor.init(), spi.begin())
